// Generated by https://quicktype.io
export interface GuitarraResponse {
    id: number;
    nombre: string;
    imagen: string;
    descripcion: string;
    precio: number;
}

export interface Carrito extends GuitarraResponse {
    cantidad: number;
}
